### ISSUE TITLE
1.3.3 `subject` extra-nesting on openssl 1.1.1d debian/buster

### ISSUE THREAD

**Issue by jaydeebee** [frdmn/openssl-cert-tools#11]
Ran into an odd issue where alexa-verifier was crashing due to its checks of `info.subject.CN`. 
 Upon investigation, `info` was actually exhibiting `info.subject.subject.CN`.  reverting to 1.3.1 does _not_ fix this, and reintroduces the `subject: {}` empty object thing.

I've traced this down to [lib/information.js line 72](https://github.com/frdmn/openssl-cert-tools/blob/master/lib/information.js#L72), where it replaces `subject= ` (mind the space), but the call to openssl on our machines yields something without a space:
```
# openssl x509 -noout -issuer -subject -dates -nameopt RFC2253 < echo-api-cert-8.pem
issuer=CN=Amazon,OU=Server CA 1B,O=Amazon,C=US
subject=CN=echo-api.amazon.com
notBefore=Mar 19 00:00:00 2020 GMT
notAfter=Mar 10 12:00:00 2021 GMT
```
OpenSSL is from Docker `debian:buster-slim`, and calls itself:
```
# openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

Suggested fix:  line 72 uses:  `.replace(/^subject= ?/, '')` instead.

**Comment by jaydeebee** [comment]
Oh, didn't think of it before (not in my use-case), but should say, `issuer` is similarly affected.

the full info object returned is:

```
{ certificate: '-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----\r\n',
  issuer: { issuer: 'CN', OU: 'Server CA 1B', O: 'Amazon', C: 'US' },
  subject: { subject: 'CN' },
  validFrom: 2020-03-19T00:00:00.000Z,
  validTo: 2021-03-10T12:00:00.000Z,
  remainingDays: 295 }
```

**Comment by frdmn** [comment]
Hi Joel, thanks for reporting! 

Can you try out version 1.3.4? It's already released on NPM and should contain a fix for this issue.

**Comment by jaydeebee** [comment]
Yep, appears to work well - thanks much!
