### ISSUE TITLE
does not support issuer and subject on openssl-1.1.x

### ISSUE THREAD

**Issue by KlausTaeger** [frdmn/openssl-cert-tools#9]

**Comment by frdmn** [comment]
Do you see any error message instead?

**Comment by frdmn** [comment]
Okay, then I'm going to try and download openssl 1.1.1a and see if I can reproduce it. One more question: What operating system do you use?

**Comment by KlausTaeger** [comment]
We are using your npm package on a docker container based on node:10-stretch, i.e. the OS is  Debian Linux (Stretch) with a 4.10.0 kernel (almost one year old).

**Comment by frdmn** [comment]
Hi Klaus,

I did some tests with OpenSSL 1.1.1 but couldn't reproduce the issue:

##### OpenSSL version

```bash
$ /usr/local/Cellar/openssl@1.1/1.1.1a/bin/openssl version
OpenSSL 1.1.1a  20 Nov 2018
```

##### Test code (with new hardcoded openssl binary path in `lib/certificate.js`

```js
var opensslTools = require('./main.js');

var host = "expired.badssl.com",
    port = 443;

opensslTools.getCertificate(host, port, function(err, crt){
    if(err){
        console.log("err",err);
    } else {
        console.log("crt",crt);
    }
});
```

##### Test code output

```
crt -----BEGIN CERTIFICATE-----
MIIFSzCCBDOgAwIBAgIQSueVSfqavj8QDxekeOFpCTANBgkqhkiG9w0BAQsFADCB
kDELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxNjA0BgNV
BAMTLUNPTU9ETyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
QTAeFw0xNTA0MDkwMDAwMDBaFw0xNTA0MTIyMzU5NTlaMFkxITAfBgNVBAsTGERv
bWFpbiBDb250cm9sIFZhbGlkYXRlZDEdMBsGA1UECxMUUG9zaXRpdmVTU0wgV2ls
ZGNhcmQxFTATBgNVBAMUDCouYmFkc3NsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMIE7PiM7gTCs9hQ1XBYzJMY61yoaEmwIrX5lZ6xKyx2PmzA
S2BMTOqytMAPgLaw+XLJhgL5XEFdEyt/ccRLvOmULlA3pmccYYz2QULFRtMWhyef
dOsKnRFSJiFzbIRMeVXk0WvoBj1IFVKtsyjbqv9u/2CVSndrOfEk0TG23U3AxPxT
uW1CrbV8/q71FdIzSOciccfCFHpsKOo3St/qbLVytH5aohbcabFXRNsKEqveww9H
dFxBIuGa+RuT5q0iBikusbpJHAwnnqP7i/dAcgCskgjZjFeEU4EFy+b+a1SYQCeF
xxC7c3DvaRhBB0VVfPlkPz0sw6l865MaTIbRyoUCAwEAAaOCAdUwggHRMB8GA1Ud
IwQYMBaAFJCvajqUWgvYkOoSVnPfQ7Q6KNrnMB0GA1UdDgQWBBSd7sF7gQs6R2lx
GH0RN5O8pRs/+zAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUE
FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwTwYDVR0gBEgwRjA6BgsrBgEEAbIxAQIC
BzArMCkGCCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8uY29tL0NQUzAI
BgZngQwBAgEwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5jb21vZG9jYS5j
b20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNybDCB
hQYIKwYBBQUHAQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LmNvbW9kb2Nh
LmNvbS9DT01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0
MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wIwYDVR0RBBww
GoIMKi5iYWRzc2wuY29tggpiYWRzc2wuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBq
evHa/wMHcnjFZqFPRkMOXxQhjHUa6zbgH6QQFezaMyV8O7UKxwE4PSf9WNnM6i1p
OXy+l+8L1gtY54x/v7NMHfO3kICmNnwUW+wHLQI+G1tjWxWrAPofOxkt3+IjEBEH
fnJ/4r+3ABuYLyw/zoWaJ4wQIghBK4o+gk783SHGVnRwpDTysUCeK1iiWQ8dSO/r
ET7BSp68ZVVtxqPv1dSWzfGuJ/ekVxQ8lEEFeouhN0fX9X3c+s5vMaKwjOrMEpsi
8TRwz311SotoKQwe6Zaoz7ASH1wq7mcvf71z81oBIgxw+s1F73hczg36TuHvzmWf
RwxPuzZEaFZcVlmtqoq8
-----END CERTIFICATE-----
```

---

Maybe you can give me a simple `docker-compose.yml` file that I can use to actually reproduce the problem?

**Comment by KlausTaeger** [comment]
Hi Jonas,

I’ll see that I send you that this weekend.

Regards,
Klaus

**Comment by silenci** [comment]
Hi,

I'm also having this issue. My openssl version is:

`$ openssl version
OpenSSL 1.1.0g  2 Nov 2017`

I've taken a look to see if I could identify the problem and I see that the command used to get information is:

`openssl x509 -noout -issuer  -subject -dates`

So, I've tried to get information from one of my certs and I get something like this (parsed info):

`$ cat files/test.pem | openssl x509 -noout -issuer  -subject -dates
issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte RSA CA 2018
subject=C = US, ST = California, L = San Francisco, O = Eighty Co., CN = *.somedomain.com
notBefore=Oct 10 00:00:00 2018 GMT
notAfter=Dec  20 12:00:00 2019 GMT`

This is exactly what is printed to my console (and to program's buffer variable too I guess...)

In your code I can see that you split issuer and subject by "/" but, as you can see in my output, there are no "/". Could this be the problem?

Regards,
Humbert

**Comment by frdmn** [comment]
@KlausTaeger @silenci Can you guys try 1.3.3 please? 😊
